# Generated by Django 3.1.1 on 2022-02-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_message_detail_agg_tbl',
            name='total_messages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
