# Generated by Django 3.1.1 on 2022-02-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_message_detail_agg_tbl_total_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_message_detail_agg_tbl',
            name='total_messages',
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='event_city_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='event_country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='event_country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='event_server_status_color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='event_server_status_severity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='total_estimated_resolution_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_message_detail_agg_tbl',
            name='total_message_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
